name: "[npmjs] npm package - Attest"

on:
  push:
    branches:
      - main 

# Permissions needed
permissions:
  contents: read
  id-token: write
  attestations: write

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      - name: Install dependencies
        working-directory: npm
        run: npm install

      - name: Build the npm package
        working-directory: npm
        run: npm run build

      - name: Attest
        uses: LedgerHQ/actions-security/actions/attest@actions/attest-1
        with:
          subject-path: npm/dist/ledger-sandbox-npm-scs-0.1.0.tgz
      - name: Attest npmjs.com
        uses: LedgerHQ/actions-security/actions/attest@actions/attest-1
        with:
          subject-name: pkg:npm/ledger-sandbox-npm-scs@0.1.0
          subject-path: npm/dist/ledger-sandbox-npm-scs-0.1.0.tgz
      
      - name: Attest npmjs.com 2
        uses: LedgerHQ/actions-security/actions/attest@actions/attest-1
        with:
          subject-name: pkg:npm/%40ledger-sandbox-npm-scs@0.1.0
          subject-path: npm/dist/ledger-sandbox-npm-scs-0.1.0.tgz

      - run: sha256sum npm/dist/ledger-sandbox-npm-scs-0.1.0.tgz

      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: '20.x'
      #     registry-url: 'https://npm.pkg.github.com'
      # - run: cd npm && npm ci
      # - run: cd npm && npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
