name: "[npmjs] npm package - Attest"

on:
  push:
    branches:
      - main 

# Permissions needed
permissions:
  contents: read
  id-token: write
  attestations: write

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      - name: Install dependencies
        working-directory: npm
        run: npm install

      - name: Build the npm package
        working-directory: npm
        run: npm run build

      - name: Attest
        uses: LedgerHQ/actions-security/actions/attest@actions/attest-1
        with:
          subject-path: npm/dist
      - name: Attest npmjs.com
        uses: LedgerHQ/actions-security/actions/attest@actions/attest-1
        with:
          subject-name: pkg:npm/ledger-sandbox-npm-scs@0.1.0
          subject-path: npm/dist

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ledger-sandbox-npm-scs-0.1.0.tgz
          path: npm/dist/ledger-sandbox-npm-scs-0.1.0.tgz
          retention-days: 1
