name: "[npmjs] npm package - Sign (blob)"

on:
  push:
    branches:
      - main 

# Permissions needed
permissions:
  contents: read
  id-token: write

jobs:
  example:
    runs-on: ledgerhq-shared-small
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      - name: Install dependencies
        working-directory: npm
        run: npm install

      - name: Build the npm package
        working-directory: npm
        run: npm run build

      - name: Sign
        uses: LedgerHQ/actions-security/actions/sign-blob@actions/sign-blob-1
        with:
          path: npm/dist
